version: "3.7"

services:
  apromore:
    image: omjadas/apromore:latest
    environment:
      IMPALA_LINK: jdbc:impala://impala:21050
      DATA_STORE: /etl_data
      JAVA_OPTS: -server -Xmx8g -Xmn1g
    depends_on:
      - db
      - impala
    volumes:
      - etl-data:/tmp/etl_data

  db:
    image: mysql:5
    command: --max_allowed_packet=2G
    environment:
      MYSQL_DATABASE: apromore
      MYSQL_ROOT_PASSWORD: MAcri
      MYSQL_USER: apromore
      MYSQL_PASSWORD: MAcri

  impala:
    image: apache/kudu:impala-latest
    volumes:
      - etl-data:/tmp/etl_data
    command: impala

volumes:
  etl-data:
