version: "3.8"

services:
  apromore:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - apromore:/apromore

  db:
    ports:
      - "3306:3306"

  impala:
    ports:
      - "21050:21050"

  logs:
    image: alpine:3
    command: tail -F /apromore/serviceability/logs/log.log
    volumes:
      - apromore:/apromore

volumes:
  apromore:
